### PR TITLE
restructuring library as a python module

### PR DESCRIPTION
**Pull request by decarboxy**
This PR restructures rf diffusion as a real python module.  There are a few reasons we should do this

* it makes it easier to run the inference script from any working directory
* it makes it easier for a user to import rfdiffusion into their own python scripts and use it as a library
* it lays the groundwork for eventually publishing rfdiffusion to pypi so it can simply be `pip install`'d

This PR does not make any functional changes to the code, a summary of the changes:

* an `__init__.py` file was added to `inference/` and `potentials/` to make them real python modules
* a new top level module `rfdiffusion/` was created. `inference/`, `potentials/` and all python files other than `run_inference.py` were moved to this module
* `run_inference.py` was movced to a new `scripts/` directory
* all imports of rfdiffusion modules were changed to absolute imports (prepended with `rfdiffusion.`)
* a setup.py file was added so `pip install` works
* two new config options `inference.schedule_directory_path` and `model_directory_path` were aded to allow the schedule cache and model directory to be located in any part of the filesystem (this is useful in cluster or container environments)
* example scripts and readme file were updated to reflect these changes.

### CODE REVIEW

**Review by joewatchwell — CHANGES_REQUESTED** [review]
Looks great - thanks for doing this. With the change to potentials/manager.py raised in my comment:
`from rfdiffusion.potentials import potentials as potentials`
All tests and examples run fine. I'll confirm with the team and then merge the changes.

**Review by nrbennet — COMMENTED** [review]
This looks good to me! Thanks for doing this!

**Comment by decarboxy** [comment]
fixed the import, updated branch and resolved conflicts

**Review by joewatchwell — APPROVED** [review]

**Review by joewatchwell — CHANGES_REQUESTED** [review]
Sorry, I think this is not properly rebased on main, as I'm still getting conflicts and thus can't merge. Would it be possible to just run `git rebase main` and fix any conflicts throughout the commit history? I think it should only be one thing in the parser.

**Review by joewatchwell — APPROVED** [review]

**Pull request merged**
