### PR TITLE
Add Dockerfile and model download script and update setup.py

### PR DESCRIPTION
**Pull request by brianloyal**
Add Dockerfile that takes into account the new package structure. Note that I also had to switch the setup.py file from distutils to setuptools to deal with an issue where the run_inference.py script couldn't import rfdiffusion.inference.

### CODE REVIEW

**Review by lyskov — APPROVED** [review]
LGTM!

**Comment by davidcjuergens** [comment]
Thanks very much for you pull request Brian -  everything looks quite nice. Would it be possible to document the Docker-enabled usage in the README file?

**Comment by brianloyal** [comment]
@davidcjuergens I added some comments on building and running the container in the README. Let me know if you see anything else. Great work on the model!

**Review by davidcjuergens — APPROVED** [review]
Looks awesome to me. Thank you very much Brian! 

DJ

**Pull request merged**
